//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DataMasker.GetUserInfo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetUserInfoSoap", Namespace="http://bceiduserinfo.gov.bc.ca/")]
    public partial class GetUserInfo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetUserbyNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback OuCountOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetUserInfo() {
            this.Url = global::DataMasker.Properties.Settings.Default.DataMasker_GetUserInfo_GetUserInfo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetUserbyNameCompletedEventHandler GetUserbyNameCompleted;
        
        /// <remarks/>
        public event OuCountCompletedEventHandler OuCountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bceiduserinfo.gov.bc.ca/GetUserbyName", RequestNamespace="http://bceiduserinfo.gov.bc.ca/", ResponseNamespace="http://bceiduserinfo.gov.bc.ca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Users[] GetUserbyName(string name) {
            object[] results = this.Invoke("GetUserbyName", new object[] {
                        name});
            return ((Users[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUserbyNameAsync(string name) {
            this.GetUserbyNameAsync(name, null);
        }
        
        /// <remarks/>
        public void GetUserbyNameAsync(string name, object userState) {
            if ((this.GetUserbyNameOperationCompleted == null)) {
                this.GetUserbyNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserbyNameOperationCompleted);
            }
            this.InvokeAsync("GetUserbyName", new object[] {
                        name}, this.GetUserbyNameOperationCompleted, userState);
        }
        
        private void OnGetUserbyNameOperationCompleted(object arg) {
            if ((this.GetUserbyNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserbyNameCompleted(this, new GetUserbyNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bceiduserinfo.gov.bc.ca/OuCount", RequestNamespace="http://bceiduserinfo.gov.bc.ca/", ResponseNamespace="http://bceiduserinfo.gov.bc.ca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OUCount[] OuCount(string ou) {
            object[] results = this.Invoke("OuCount", new object[] {
                        ou});
            return ((OUCount[])(results[0]));
        }
        
        /// <remarks/>
        public void OuCountAsync(string ou) {
            this.OuCountAsync(ou, null);
        }
        
        /// <remarks/>
        public void OuCountAsync(string ou, object userState) {
            if ((this.OuCountOperationCompleted == null)) {
                this.OuCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOuCountOperationCompleted);
            }
            this.InvokeAsync("OuCount", new object[] {
                        ou}, this.OuCountOperationCompleted, userState);
        }
        
        private void OnOuCountOperationCompleted(object arg) {
            if ((this.OuCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OuCountCompleted(this, new OuCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bceiduserinfo.gov.bc.ca/")]
    public partial class Users {
        
        private string displaynameField;
        
        private string givenNameField;
        
        private string snField;
        
        private string bcgovguidField;
        
        private string primarySMTPAddressField;
        
        private string mailField;
        
        private string samaccountnameField;
        
        private string userprincipalnameField;
        
        private string titleField;
        
        private string departmentField;
        
        private string telephoneNumberField;
        
        private string streetAddressField;
        
        private string uSNChangedField;
        
        /// <remarks/>
        public string displayname {
            get {
                return this.displaynameField;
            }
            set {
                this.displaynameField = value;
            }
        }
        
        /// <remarks/>
        public string givenName {
            get {
                return this.givenNameField;
            }
            set {
                this.givenNameField = value;
            }
        }
        
        /// <remarks/>
        public string sn {
            get {
                return this.snField;
            }
            set {
                this.snField = value;
            }
        }
        
        /// <remarks/>
        public string bcgovguid {
            get {
                return this.bcgovguidField;
            }
            set {
                this.bcgovguidField = value;
            }
        }
        
        /// <remarks/>
        public string PrimarySMTPAddress {
            get {
                return this.primarySMTPAddressField;
            }
            set {
                this.primarySMTPAddressField = value;
            }
        }
        
        /// <remarks/>
        public string mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        public string samaccountname {
            get {
                return this.samaccountnameField;
            }
            set {
                this.samaccountnameField = value;
            }
        }
        
        /// <remarks/>
        public string userprincipalname {
            get {
                return this.userprincipalnameField;
            }
            set {
                this.userprincipalnameField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string TelephoneNumber {
            get {
                return this.telephoneNumberField;
            }
            set {
                this.telephoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string StreetAddress {
            get {
                return this.streetAddressField;
            }
            set {
                this.streetAddressField = value;
            }
        }
        
        /// <remarks/>
        public string uSNChanged {
            get {
                return this.uSNChangedField;
            }
            set {
                this.uSNChangedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bceiduserinfo.gov.bc.ca/")]
    public partial class OUCount {
        
        private string organizationUnitField;
        
        private int oRganizationUnitCountField;
        
        /// <remarks/>
        public string OrganizationUnit {
            get {
                return this.organizationUnitField;
            }
            set {
                this.organizationUnitField = value;
            }
        }
        
        /// <remarks/>
        public int ORganizationUnitCount {
            get {
                return this.oRganizationUnitCountField;
            }
            set {
                this.oRganizationUnitCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetUserbyNameCompletedEventHandler(object sender, GetUserbyNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserbyNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserbyNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Users[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Users[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void OuCountCompletedEventHandler(object sender, OuCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OuCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OuCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OUCount[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OUCount[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591